//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_mvc_5_2_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual TaskEmployee TaskEmployee { get; set; }
    }
}
