//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_mvc_5_2_2023.Models
{
    using System;   
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class TaskEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskEmployee()
        {
            this.orders = new HashSet<order>();
        }
    
        public int Id { get; set; }
        //
        [Required]
        [StringLength(12, ErrorMessage = "The Max Character of Name is 12 characters")]
        [DisplayName("First Name")]
        public string First_Name { get; set; }
        //
        [DisplayName("Last Name")]
        [Required]
        [StringLength(12, ErrorMessage = "The Max Character of Name is 12 characters")]
        public string Last_Name { get; set; }
        //
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        //
        [Required]
        [RegularExpression("((079)|(078)|(077)){1}[0-9]{7}", ErrorMessage = "Number must be Joirdanian")]

        public string Phone { get; set; }
        //
        [Required]
        [Range(18, 50)]
        public Nullable<int> Age { get; set; }
        //
        [Required]
        [MaxLength(10), MinLength(1)]
        [DisplayName("Job Title")]
        public string Job_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string CV { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
